In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
data=pd.read_csv("New_online_sales.csv")
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,DateTime
0,221958,SKU_1964,White Mug,38,01-01-2020 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,01-01-2020
1,771155,SKU_1241,White Mug,18,01-01-2020 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,01-01-2020
2,231932,SKU_1501,Headphones,49,01-01-2020 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,01-01-2020
3,465838,SKU_1760,Desk Lamp,14,01-01-2020 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,01-01-2020
4,359178,SKU_1386,USB Cable,-30,01-01-2020 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium,01-01-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,05-09-2025 01:00,70.92,51445.0,Spain,0.200000,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,05-09-2025
49778,296698,SKU_1930,USB Cable,7,05-09-2025 02:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,05-09-2025
49779,177622,SKU_1766,Office Chair,43,05-09-2025 03:00,85.25,21825.0,Portugal,0.200000,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,05-09-2025
49780,701213,SKU_1602,Notebook,48,05-09-2025 04:00,39.64,43199.0,United Kingdom,0.310000,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,05-09-2025
49781,772215,SKU_1832,White Mug,30,05-09-2025 05:00,38.27,53328.0,France,0.100000,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,05-09-2025

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49782 entries, 0 to 49781
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InvoiceNo          49782 non-null  int64
 1   StockCode          49782 non-null  object
 2   Description        49782 non-null  object
 3   Quantity           49782 non-null  int64
 4   InvoiceDate        49782 non-null  object
 5   UnitPrice          49782 non-null  float64
 6   CustomerID         44804 non-null  float64
 7   Country            49782 non-null  object
 8   Discount           49782 non-null  float64
 9   PaymentMethod      49782 non-null  object
 10  ShippingCost       47293 non-null  float64
 11  Category           49782 non-null  object
 12  SalesChannel       49782 non-null  object
 13  ReturnStatus       49782 non-null  object
 14  ShipmentProvider   49782 non-null  object
 15  WarehouseLocation  46297 non-null  object
 16  OrderPriority      49782 non-null  object
 17  DateTime           49782 non-null  object
dtypes: float64(4), int64(2), object(12)
memory usage: 6.8+ MB

In [10]:
data.isnull().sum()

InvoiceNo               0
StockCode               0
Description             0
Quantity                0
InvoiceDate             0
UnitPrice               0
CustomerID           4978
Country                 0
Discount                0
PaymentMethod           0
ShippingCost         2489
Category                0
SalesChannel            0
ReturnStatus            0
ShipmentProvider        0
WarehouseLocation    3485
OrderPriority           0
DateTime                0
dtype: int64

In [11]:
data.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,DateTime
49777,354083,SKU_1562,Blue Pen,25,05-09-2025 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,05-09-2025
49778,296698,SKU_1930,USB Cable,7,05-09-2025 02:00,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,05-09-2025
49779,177622,SKU_1766,Office Chair,43,05-09-2025 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,05-09-2025
49780,701213,SKU_1602,Notebook,48,05-09-2025 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,05-09-2025
49781,772215,SKU_1832,White Mug,30,05-09-2025 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,05-09-2025

In [12]:
data.dropna(inplace=True)
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,DateTime
0,221958,SKU_1964,White Mug,38,01-01-2020 00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,01-01-2020
1,771155,SKU_1241,White Mug,18,01-01-2020 01:00,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,01-01-2020
2,231932,SKU_1501,Headphones,49,01-01-2020 02:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,01-01-2020
3,465838,SKU_1760,Desk Lamp,14,01-01-2020 03:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,01-01-2020
5,744167,SKU_1006,Office Chair,47,01-01-2020 05:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium,01-01-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,05-09-2025 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,05-09-2025
49778,296698,SKU_1930,USB Cable,7,05-09-2025 02:00,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,05-09-2025
49779,177622,SKU_1766,Office Chair,43,05-09-2025 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,05-09-2025
49780,701213,SKU_1602,Notebook,48,05-09-2025 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,05-09-2025
49781,772215,SKU_1832,White Mug,30,05-09-2025 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,05-09-2025

In [13]:
data.isnull().sum()

InvoiceNo            0
StockCode            0
Description          0
Quantity             0
InvoiceDate          0
UnitPrice            0
CustomerID           0
Country              0
Discount             0
PaymentMethod        0
ShippingCost         0
Category             0
SalesChannel         0
ReturnStatus         0
ShipmentProvider     0
WarehouseLocation    0
OrderPriority        0
DateTime             0
dtype: int64

In [18]:
data[data["CustomerID"].isnull()]
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,DateTime
0,221958,SKU_1964,White Mug,38,01-01-2020 00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,01-01-2020
1,771155,SKU_1241,White Mug,18,01-01-2020 01:00,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,01-01-2020
2,231932,SKU_1501,Headphones,49,01-01-2020 02:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,01-01-2020
3,465838,SKU_1760,Desk Lamp,14,01-01-2020 03:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,01-01-2020
5,744167,SKU_1006,Office Chair,47,01-01-2020 05:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium,01-01-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,05-09-2025 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,05-09-2025
49778,296698,SKU_1930,USB Cable,7,05-09-2025 02:00,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,05-09-2025
49779,177622,SKU_1766,Office Chair,43,05-09-2025 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,05-09-2025
49780,701213,SKU_1602,Notebook,48,05-09-2025 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,05-09-2025
49781,772215,SKU_1832,White Mug,30,05-09-2025 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,05-09-2025

In [21]:
a=data.count().max()
print(a)

44804

In [25]:
data.dtypes

InvoiceNo              int64
StockCode             object
Description           object
Quantity               int64
InvoiceDate           object
UnitPrice            float64
CustomerID           float64
Country               object
Discount             float64
PaymentMethod         object
ShippingCost         float64
Category              object
SalesChannel          object
ReturnStatus          object
ShipmentProvider      object
WarehouseLocation     object
OrderPriority         object
DateTime              object
dtype: object

In [30]:
# Step 1: Parse the datetime with correct settings
data["InvoiceDate"] = pd.to_datetime(data["InvoiceDate"], dayfirst=True, errors='coerce')

# Step 2: Extract only the date part
data["InvoiceDate"] = data["InvoiceDate"].dt.date
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,DateTime
0,221958,SKU_1964,White Mug,38,2020-01-01,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,01-01-2020
1,771155,SKU_1241,White Mug,18,2020-01-01,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,01-01-2020
2,231932,SKU_1501,Headphones,49,2020-01-01,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,01-01-2020
3,465838,SKU_1760,Desk Lamp,14,2020-01-01,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,01-01-2020
5,744167,SKU_1006,Office Chair,47,2020-01-01,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium,01-01-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,05-09-2025
49778,296698,SKU_1930,USB Cable,7,2025-09-05,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,05-09-2025
49779,177622,SKU_1766,Office Chair,43,2025-09-05,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,05-09-2025
49780,701213,SKU_1602,Notebook,48,2025-09-05,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,05-09-2025
49781,772215,SKU_1832,White Mug,30,2025-09-05,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,05-09-2025

In [37]:
data.drop("DateTime",axis=1,inplace=True)
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
5,744167,SKU_1006,Office Chair,47,2020-01-01,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [32]:
data.isnull().sum()

InvoiceNo            0
StockCode            0
Description          0
Quantity             0
InvoiceDate          0
UnitPrice            0
CustomerID           0
Country              0
Discount             0
PaymentMethod        0
ShippingCost         0
Category             0
SalesChannel         0
ReturnStatus         0
ShipmentProvider     0
WarehouseLocation    0
OrderPriority        0
DateTime             0
dtype: int64

In [38]:
data.to_csv("New_online_sales",index=False)

In [41]:
data.to_csv(r'C:\Users\ganesh r. gawde\OneDrive\Desktop\Data anlysis project\New_sales_data.csv', index=False)

In [40]:
import os

file_path = r'D:\DataCleaning\Output\New_sales_data.csv'

if os.path.exists(file_path):
    print("✅ File saved successfully!")
else:
    print("❌ File not found. Check folder path and permissions.")

❌ File not found. Check folder path and permissions.